name: ${APP_NAME:-ptracker}

services:
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ptracker
      MYSQL_PASSWORD: omgverysecret
      MYSQL_DATABASE: nurse_joy
    volumes:
      - issp_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    depends_on:
      - db
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64

    environment:
      DATABASE_URL: "mysql://ptracker:omgverysecret@db:3306/nurse_joy"
      DATABASE_URL_TESTING: "mysql://ptracker:omgverysecret@db:3306/nurse_joy_testing"
      APP_URL: http://localhost:8000
      DEBUG: true
      CI: false

    ports:
      - 3000:3000

volumes:
  issp_db_data:
